### ISSUE TITLE
Underscore in hostname = Could not connect to SMTP host

### ISSUE THREAD

**Issue by soywod** [PHPMailer/PHPMailer#1381]
Hi,
I'm working on a mail project running on docker (managed by docker-compose), and it seems that PHPMailer is not able to reach the neighbor container linked by its name. I have 2 containers : one named `mail_api` (which contains a PHP API, PHPMailer is here) and an other one named `mail_server` (the imap server). When I try to connect to the SMTP server, I got this error : 

```
SMTP Error: Could not connect to SMTP host. mail_server
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```
Here the code : 

```
$mail = new PHPMailer(true);                                                                                                        
                                                                                                                                      $mail->SMTPDebug = 4;                                                                                                               
$mail->isSMTP();
$mail->Host = getenv('HOST');                                                                                                       
$mail->SMTPAuth = true;
$mail->Username = getenv('USERNAME');
$mail->Password = getenv('PASSWORD');
$mail->SMTPSecure = 'tls';
$mail->Port = 25;
$mail->SMTPOptions = array(
  'starttls' => array(
     'verify_peer' => false,
      'verify_peer_name' => false,
      'allow_self_signed' => true
  )
);

$mail->setFrom(getenv('EMAIL'));
$mail->addAddress($params['to']);

$mail->isHTML(false);
$mail->Subject = $params['subject'];
$mail->Body = $params['body'];
$mail->AltBody = $params['body'];

$mail->send();
```
I know it's not coming from my server, because everything is working here. I can connect to this server with other clients like Thunderbird and I can receive / send mails. And I know this hostname `mail_server` is ok because I use it for the IMAP connection earlier in the code, and it works like a charm : 

```
function getConnection(): Connection {
  $imap = new ImapServer(getenv('HOST'), 143, '/imap/tls/novalidate-cert');
  return $imap->authenticate(getenv('USERNAME'), getenv('PASSWORD'));
}
```

The docker-compose version is the version 2, and the container is linked this way : 

```
  mail_api:
    container_name: mail_api
    build: ./mail-api
    environment:
      - HOST=${MAIL_API_HOST}
      - EMAIL=${MAIL_USERNAME}@${MAIL_DOMAIN}
      - USERNAME=${MAIL_USERNAME}
      - PASSWORD=${MAIL_PASSWORD}
    ports:
      - "${MAIL_API_PORT}:80"
    volumes:
      - ./mail-api:/app
    links:
      - mail_server

```

Any idea ?
